apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuntal
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: csvserver
          image: sandipholambe/csvserver:latest
          volumeMounts:
            - name: my-volume
              mountPath: /csvserver/inputdata
          ports:
            - containerPort: 9393
          env:
            - name: BORDER_COLOR
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: border-color
        - name: prometheus
          image: prom/prometheus:v2.22.0
          ports:
            - containerPort: 9090
      volumes:
        - name: my-volume
          configMap:
            name: config
