web:
  image: sandipholambe/csvserver:latest
  container_name: kuntal
  ports:
    - 9393:9300
  volumes:
    - ./inputFile:/csvserver/inputdata
  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
     - 9090:9090
